### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by spolanski** [YangShen398/F3D-ODB-Reader-Plugin#2]
Hello,
I am just about to test this work and I think it is great this exist.

Could you please tell if this project converts Abaqus ODB file to VTK in the background? I am wondering if it could be used in Paraview directly.

Thank you
Slaw

**Comment by yangcshen** [comment]
Hi Slaw,

If you need to convert ODB file to VTK, I would recommend another [repo](https://github.com/Arris-Composites/ODB2VTK)
This project basically stems from ODB2VTK and it is not as robust as ODB2VTK.

**Comment by yangcshen** [comment]
Hi Slaw,

I am closing this issue now. If you have other questions regarding converting ODB to VTK. You can ask them in that [repo](https://github.com/Arris-Composites/ODB2VTK).

Thanks,
Yang
